package uz.pdp.online_university.config;

import uz.pdp.online_university.enums.PermissionCatalog;
import uz.pdp.online_university.enums.RoleName;

import java.util.Map;
import java.util.Set;

import static uz.pdp.online_university.enums.PermissionCatalog.*;

public final class RolePermissionMapping {

    private RolePermissionMapping() {
    }

    public static final Map<RoleName, Set<PermissionCatalog>> MATRIX = Map.of(

            RoleName.ADMIN, Set.of(
                    USER_CREATE, USER_READ, USER_UPDATE, USER_DEACTIVATE,
                    USER_ROLE_ASSIGN, USER_SESSION_TERMINATE, USER_PASSWORD_RESET,
                    ADMISSION_APPLICATION_READ, ADMISSION_APPLICATION_REVIEW,
                    ADMISSION_EXAM_SCHEDULE, ADMISSION_DECISION_MAKE,
                    ACADEMIC_PROGRAM_CREATE, ACADEMIC_PROGRAM_READ, ACADEMIC_PROGRAM_UPDATE,
                    ACADEMIC_GROUP_MANAGE, ACADEMIC_SCHEDULE_MANAGE,
                    ACADEMIC_OVERRIDE_CREATE, ACADEMIC_ESCALATION_CREATE,
                    COURSE_READ, LECTURE_READ, MATERIAL_READ,
                    ASSESSMENT_ASSIGNMENT_READ, ASSESSMENT_SUBMISSION_READ,
                    ASSESSMENT_GRADE_READ, ASSESSMENT_EXAM_SCHEDULE,
                    ASSESSMENT_APPEAL_REVIEW, ASSESSMENT_RETAKE_MANAGE,
                    ATTENDANCE_READ, ATTENDANCE_MANAGE,
                    COMMUNICATION_CHAT_READ,
                    FINANCE_CONTRACT_CREATE, FINANCE_CONTRACT_READ,
                    FINANCE_PAYMENT_READ, FINANCE_BLOCK_MANAGE, FINANCE_REPORT_READ,
                    AQAD_COMPLAINT_READ, AQAD_REPORT_READ,
                    RESOURCE_WORKLOAD_READ,
                    DASHBOARD_KPI_READ, DASHBOARD_ANALYTICS_READ, DASHBOARD_REPORT_EXPORT,
                    SYSTEM_CONFIG_MANAGE, SYSTEM_AUDIT_READ,
                    SYSTEM_INTEGRATION_MANAGE, SYSTEM_MONITOR_READ
            ),

            RoleName.TEACHER, Set.of(
                    ACADEMIC_PROGRAM_READ,
                    COURSE_CREATE, COURSE_READ, COURSE_UPDATE, COURSE_DELETE, COURSE_SUBMIT_REVIEW,
                    LECTURE_CREATE, LECTURE_READ, LECTURE_UPDATE, LECTURE_DELETE, LECTURE_CONDUCT,
                    MATERIAL_UPLOAD, MATERIAL_READ, MATERIAL_UPDATE, MATERIAL_DELETE,
                    ASSESSMENT_ASSIGNMENT_CREATE, ASSESSMENT_ASSIGNMENT_READ,
                    ASSESSMENT_SUBMISSION_READ, ASSESSMENT_GRADE_CREATE, ASSESSMENT_GRADE_READ,
                    ASSESSMENT_EXAM_CONDUCT, ASSESSMENT_APPEAL_REVIEW,
                    ATTENDANCE_READ, ATTENDANCE_MANAGE,
                    COMMUNICATION_CHAT_SEND, COMMUNICATION_CHAT_READ,
                    COMMUNICATION_QA_CREATE, COMMUNICATION_QA_ANSWER, COMMUNICATION_QA_MODERATE,
                    COMMUNICATION_COMMENT_CREATE, COMMUNICATION_COMMENT_MODERATE
            ),

            RoleName.STUDENT, Set.of(
                    ACADEMIC_PROGRAM_READ,
                    COURSE_READ, LECTURE_READ, MATERIAL_READ,
                    ASSESSMENT_ASSIGNMENT_READ, ASSESSMENT_SUBMISSION_CREATE,
                    ASSESSMENT_GRADE_READ, ASSESSMENT_APPEAL_CREATE,
                    ATTENDANCE_READ,
                    COMMUNICATION_CHAT_SEND, COMMUNICATION_CHAT_READ,
                    COMMUNICATION_QA_CREATE, COMMUNICATION_QA_ANSWER,
                    COMMUNICATION_COMMENT_CREATE,
                    FINANCE_CONTRACT_READ, FINANCE_PAYMENT_READ
            ),

            RoleName.APPLICANT, Set.of(
                    ADMISSION_APPLICATION_READ,
                    ASSESSMENT_SUBMISSION_CREATE
            ),

            RoleName.ACADEMIC_DEPARTMENT, Set.of(
                    USER_READ,
                    ADMISSION_APPLICATION_READ, ADMISSION_APPLICATION_REVIEW,
                    ADMISSION_EXAM_SCHEDULE, ADMISSION_DECISION_MAKE,
                    ACADEMIC_PROGRAM_CREATE, ACADEMIC_PROGRAM_READ, ACADEMIC_PROGRAM_UPDATE,
                    ACADEMIC_GROUP_MANAGE, ACADEMIC_SCHEDULE_MANAGE,
                    ACADEMIC_OVERRIDE_CREATE, ACADEMIC_ESCALATION_CREATE,
                    COURSE_READ, LECTURE_READ, MATERIAL_READ,
                    ASSESSMENT_ASSIGNMENT_READ, ASSESSMENT_SUBMISSION_READ,
                    ASSESSMENT_GRADE_READ, ASSESSMENT_EXAM_SCHEDULE,
                    ASSESSMENT_APPEAL_REVIEW, ASSESSMENT_RETAKE_MANAGE,
                    ATTENDANCE_READ, ATTENDANCE_MANAGE,
                    COMMUNICATION_CHAT_READ,
                    FINANCE_CONTRACT_READ, FINANCE_PAYMENT_READ, FINANCE_REPORT_READ,
                    AQAD_COMPLAINT_READ, AQAD_REPORT_READ,
                    RESOURCE_WORKLOAD_READ,
                    DASHBOARD_KPI_READ, DASHBOARD_REPORT_EXPORT
            ),

            RoleName.AQAD, Set.of(
                    ACADEMIC_PROGRAM_READ,
                    COURSE_READ, LECTURE_READ, MATERIAL_READ,
                    ASSESSMENT_ASSIGNMENT_READ, ASSESSMENT_SUBMISSION_READ, ASSESSMENT_GRADE_READ,
                    ATTENDANCE_READ,
                    COMMUNICATION_CHAT_READ,
                    COMMUNICATION_QA_MODERATE, COMMUNICATION_COMMENT_MODERATE,
                    AQAD_REVIEW_CONDUCT, AQAD_REVIEW_DECIDE, AQAD_AUDIT_CONDUCT,
                    AQAD_COMPLAINT_READ, AQAD_COMPLAINT_MANAGE,
                    AQAD_CORRECTIVE_CREATE, AQAD_REPORT_READ,
                    DASHBOARD_KPI_READ, DASHBOARD_REPORT_EXPORT
            ),

            RoleName.FINANCE, Set.of(
                    FINANCE_CONTRACT_CREATE, FINANCE_CONTRACT_READ,
                    FINANCE_PAYMENT_READ, FINANCE_PAYMENT_SYNC,
                    FINANCE_BLOCK_MANAGE, FINANCE_REPORT_READ,
                    DASHBOARD_KPI_READ
            ),

            RoleName.RESOURCE_DEPARTMENT, Set.of(
                    USER_READ,
                    RESOURCE_TEACHER_REGISTER, RESOURCE_TEACHER_ASSIGN,
                    RESOURCE_WORKLOAD_READ, RESOURCE_REPLACEMENT_MANAGE,
                    DASHBOARD_KPI_READ
            ),

            RoleName.DEPUTY_DIRECTOR, Set.of(
                    ACADEMIC_PROGRAM_READ,
                    COURSE_READ, LECTURE_READ, MATERIAL_READ,
                    ASSESSMENT_GRADE_READ,
                    ATTENDANCE_READ,
                    FINANCE_CONTRACT_READ, FINANCE_PAYMENT_READ, FINANCE_REPORT_READ,
                    AQAD_COMPLAINT_READ, AQAD_REPORT_READ,
                    RESOURCE_WORKLOAD_READ,
                    DASHBOARD_KPI_READ, DASHBOARD_ANALYTICS_READ, DASHBOARD_REPORT_EXPORT,
                    SYSTEM_AUDIT_READ, SYSTEM_MONITOR_READ
            ),

            RoleName.IT_OPERATIONS, Set.of(
                    SYSTEM_CONFIG_MANAGE, SYSTEM_AUDIT_READ,
                    SYSTEM_INTEGRATION_MANAGE, SYSTEM_MONITOR_READ
            )
    );
}
